# Site
name: 'Filtered Snippets'
description: 'Filtered Snippets is a travel, lifestyle and food blog by a digital nomad and expat.'
logo: 
favicon: 'assets/images/favicon.ico'

# disqus: 'filteredsnippets.github.io'
# email: 'wowthemesnet@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    kitty:
      name:           Kitty
      site:           
      avatar:         assets/images/avatar2.jpg
      bio:            "<p>Hi, I'm Kitty a digital nomad and expat working in sustainability education. 
                      I created Filtered Snippets to share tips and information about travel, food, and global and sustainable living. 
                      In 2016, I started working remotely in educational publishing and moved to Spain for love. Working remotely  
                      has given me the luxury of being location independent and allowed me to explore 
                      many parts of Europe, as well as Latin America and Asia.</p>                      
                                            
                      <b>Education</b><br>
                      <ul>
                      <li>Master of Science in Education & Sustainability | Gothenburg University, Sweden (2018-present)</li>
                      <li>Master of Science in Digital Humanities | KU Leuven, Belgium (2018-2019)</li>
                      <li>Master of Arts in Applied Linguistics-TEFL | Groningen University, the Netherlands (2013-2014)</li>
                      <li>Bachelor of Arts in English Language and Culture | Groningen University, the Netherlands (2010-2013)</li></ul>-->"
      instagram:      https://www.instagram.com/filteredsnippets/?hl=en
      pinterest:      https://www.pinterest.com/filteredsnippets

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: kitty
      avatar: /assets/images/avatar2.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Excerpts


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Google-analytics
google-analytics:
  id: "UA-165399745-1"
