# Site
name: 'Filtered Snippets'
description: 'Filtered Snippets is a travel, lifestyle and food blog by a digital nomad and expat.'
logo: 
favicon: 'assets/images/favicon.ico'

# disqus: 'filteredsnippets.github.io'
# email: 'wowthemesnet@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    kitty:
      name:           Kitty
      site:           
      avatar:         assets/images/avatar2.jpg
      bio:            "<p>Hi, I'm Kitty a digital nomad and expat working in language and sustainability education. 
                      On Filtered Snippets you'll find my (food) travel and hiking tips and recipes.</p> 
                      <p>In 2016, I started working remotely in educational publishing and moved to Spain for love. Working remotely  
                      has given me the luxury of being location independent and allowed me to explore and eat my way
                      through Europe, Latin America, and Asia.</p>
                      <p>Over the years I have become more concerned with the environmental impact
                      of my lifestyle and I have incorporated small, but also larger changes to live more consciously and sustainably. I avoid animal products
                      as much as possible at home, but I do endulge when traveling. 
                      Via Filtered Snippets I hope to share my exploration of the world and food, often through a more sustainable lens.</p>"
      instagram:      https://www.instagram.com/filteredsnippets/?hl=en
      pinterest:      https://www.pinterest.com/filteredsnippets

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: kitty
      avatar: /assets/images/avatar2.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Excerpts


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Google-analytics
google-analytics:
  id: "UA-165399745-1"
